---
apiVersion: app/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      container:
        - name: nginx-deployment
          image: nginx
          ports:
            - containerPort: 80
