---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express-backend
spec:
  selector:
    matchLabels:
      app: mongo-express-backend
  template:
    metadata:
      labels:
        app: mongo-express-backend
    spec:
      containers:
        - name: mongo-express-backend
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: dbuser
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: dbpass
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: database_url

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-ext-service
spec:
  selector:
    app: mongo-express-backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 31080
